apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline-manager-config
  namespace: elastic-stack
data:
  pipelines.yml: |-
    # The ID of the pipeline.
    - pipeline.id: main

    # The path to the Logstash config for the main pipeline
      path.config: "/usr/share/logstash/pipeline/main"

    # Is available to plugins that implement an ECS compatibility mode for use with the Elastic Common Schema
      pipeline.ecs_compatibility: disabled