spec:
  receiver: alert-email
  group_by:
    - container
    - workload
    - alertname
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 24h
  match:
    type: container

---
spec:
  receiver: alert-email-infra
  group_by:
    - node
    - instance
    - alertname
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 24h
  match:
    type: infra